### ISSUE TITLE
To build arm64 artifacts we need an Apple silicon custom runner

### ISSUE THREAD

**Issue by hannesa2** [gitx/gitx#289] opened 2022-02-17 07:06 UTC
At least for release we will need it to sign the artifacts for `arm64`

e.g
* https://github.com/actions/runner/issues/805
* https://github.com/actions/runner/pull/1618 (**This is the most promising !**)
* https://github.com/mas-cli/m1-github-actions-runner
* https://gregmfoster.medium.com/using-m1-mac-minis-to-power-our-github-actions-ios-ci-540c55af13ea
* https://www.mirkogalimberti.com/post/2/github-actions-self-hosted-apple-silicon-m1-runner-howto

**Comment by niksy** [comment] 2022-05-21 06:15
This seems to be merged and will be available next Monday! Could we get started on building for ARM?

**Comment by hannesa2** [comment] 2022-05-21 06:21
https://github.com/actions/runner/pull/1618#issuecomment-1133366112
Sure, we need a self hosted runner, then we can do this.
I can offer such a self hosted runner at the beginning, but I've no clue how to set it up.

**Comment by niksy** [comment] 2022-05-22 06:54
No idea here also 😄 

Maybe some of the links in original post can help? Also, I see that MacStadium offers Mac runners for open source projects so maybe that can be leveraged?

https://github.com/ranisalt/node-argon2/issues/305#issuecomment-1023118057

**Closed** 2022-05-27 12:01 UTC

**Comment by hannesa2** [comment] 2022-05-27 12:16
I built this new release https://github.com/gitx/gitx/releases/tag/0.20 with the new arm64 runner

**Comment by niksy** [comment] 2022-05-27 13:11
Just tried it, works as intended!

**Comment by hannesa2** [comment] 2022-06-07 11:50
Now it builds every pull request with a M1 https://github.com/gitx/gitx/pull/314
