### ISSUE TITLE
Hard CPU pressure on background.

### ISSUE THREAD

**Issue by vng** [gitx/gitx#102] opened 2017-09-29 11:35 UTC
- Build latest master.
- Open any repo.
- Switch to code editor and edit any file from the repo with saving. GitX starts some activity that pressure all available cores.

**Comment by robinwhittleton** [comment] 2017-09-29 12:11
I’ve noticed this too, although I put it down to the fact that I had multiple 1mb unmerged epubs sitting in the repo.

**Comment by beporter** [comment] 2017-10-09 12:06
For me the CPU spikes when I start running my `phpunit` test suite against the checked out repo. Bringing GitX to the front momentarily seems to resolve the issue until the next test suite run. I can usually tell this is happening because it's the only time the fan in my MacBook turns on. 😞

**Comment by tiennou** [comment] 2017-10-09 13:56
Sorry, I don't remember whether something related to how GitX run command-line tasks has been merged yet or not (I think not), but if my memory isn't faulty, you guys are running with the "Automatic refresh" thingy enabled (see GitX preferences), and it can cause major issues when 1) there's major filesystem churn going on 2) you use `git` to perform rebases (because locking).

It's actually best to disable it and manually refresh (⌘R) when switching to GitX.

**Comment by vng** [comment] 2017-10-11 06:23
@tiennou If you mean "Watch for changes in repositories", this option is off for me, but the problem still exists. I didn't find any other "Automatic refresh" option.

**Comment by mangerlahn** [comment] 2017-12-01 21:12
I think I found the issue. 

The addition of 

	fileHandle.readabilityHandler = ^(NSFileHandle * _Nonnull fileHandle) {
		[dataOutput appendData:fileHandle.availableData];
	};

in 7057740cf6035e5a1dbb97d4c2e846ef89029e6f causes the CPU load. If I comment this section out, the issue is gone (for me!)..

The lines can be found in `- (void)setDataOutput:(nonnull NSMutableData *)dataOutput;` of `PBEasyPipe`.

**Comment by mangerlahn** [comment] 2017-12-01 21:17
Maybe @claybridges can help?

**Comment by tiennou** [comment] 2017-12-02 17:07
Might be caused by [this](https://stackoverflow.com/questions/13747232/using-nstask-and-nspipe-causes-100-cpu-usage). Does adding `[self.fileHandleForReading closeFile]` to that `-clear` method makes it go away ? I suspect there's a retain loop somewhere, which would cause the task to linger, causing the pipe to not be closed.

**Comment by mangerlahn** [comment] 2017-12-02 18:26
You were right! Closing the handle relaxes the situation.. Thanks!

**Closed** 2017-12-04 13:32 UTC

**Comment by mitisBlack** [comment] 2018-01-29 13:43
@tiennou the fix for this is not quite correct. See the second answer on the stackoverflow link. If the file is not complete (or read completely), the sub-process will fail with a SIGPIPE abort. I can reproduce this easily when attempting to amend a patch with many changed files (eg: updated smth  across all .h files in a project).

**Comment by robinwhittleton** [comment] 2018-01-29 13:53
Thanks for the diagnosis @mitisBlack. GitX has definitely been quite explosive for me since this merge. For example, I had to give use using GitX and switch to Fork to review the changes in this commit: https://github.com/robinwhittleton/herman-melville_moby-dick/commit/26af2232b45edee18291dad21e42b84c6c9587f7. Feel free to clone the repo and soft reset to try to replicate if you want.

**Comment by tiennou** [comment] 2018-02-05 21:05
Just pushed a fix to master for the 2nd part, and checked that the Moby Dick repo works (thanks for that @robinwhittleton, that's a pretty helpful test case 😉).
