### ISSUE TITLE
Error opening gitx from commandline after update to 1.0

### ISSUE THREAD

**Issue by predominant** [gitx/gitx#398] opened 2023-04-12 06:28 UTC
```
$ gitx
2023-04-12 15:26:42.230 gitx[17339:6537002] warning: failed to get scripting definition from /Applications/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app; it may not be scriptable.
2023-04-12 15:26:42.230 gitx[17339:6537002] -[SBApplication open:withOptions:]: unrecognized selector sent to instance 0x6000014e8000
2023-04-12 15:26:42.230 gitx[17339:6537002] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBApplication open:withOptions:]: unrecognized selector sent to instance 0x6000014e8000'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8026eb773 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80244bbc3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff80277035b -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007ff802652535 ___forwarding___ + 1356
	4   CoreFoundation                      0x00007ff802651f58 _CF_forwarding_prep_0 + 120
	5   gitx                                0x000000010be156e6 gitx + 5862
	6   gitx                                0x000000010be16616 gitx + 9750
	7   dyld                                0x0000000110de952e start + 462
)
libc++abi: terminating with uncaught exception of type NSException
[1]    17339 abort      gitx
```

**Comment by hannesa2** [comment] 2023-04-12 06:33
duplicate of https://github.com/gitx/gitx/issues/397 and a solution is here https://github.com/gitx/gitx/issues/397#issuecomment-1503413204

But I guess nobody knows the root cause

**Closed by hannesa2** 2023-04-12 06:33 UTC
