### ISSUE TITLE
`gitx` command line not working correctly

### ISSUE THREAD

**Issue by chief1983** [gitx/gitx#403] opened 2023-04-18 00:13 UTC
OS: MacOS Ventura 13.3.1 (Intel)

Previously, just typing `gitx` in the command line inside a repo would open the repo in GitX.  Now, I get the following:

```
2023-04-17 19:07:33.782 gitx[46145:6561608] warning: failed to get scripting definition from /Applications/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app; it may not be scriptable.
2023-04-17 19:07:33.782 gitx[46145:6561608] -[SBApplication open:withOptions:]: unrecognized selector sent to instance 0x6000021f8a50
2023-04-17 19:07:33.782 gitx[46145:6561608] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBApplication open:withOptions:]: unrecognized selector sent to instance 0x6000021f8a50'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80e56a1ba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80e09042b objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff80e60601f -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007ff80e4d58d7 ___forwarding___ + 1392
	4   CoreFoundation                      0x00007ff80e4d52d8 _CF_forwarding_prep_0 + 120
	5   gitx                                0x0000000106f3e6e6 gitx + 5862
	6   gitx                                0x0000000106f3f616 gitx + 9750
	7   dyld                                0x00007ff80e0bd41f start + 1903
)
libc++abi: terminating due to uncaught exception of type NSException
Abort trap: 6
```

I noticed that it is saying something about the updater, and so I'll also mention here that the `Check Now` button in the Settings menu doesn't seem to be working either.

To work-around, I have been running GitX with Cmd+Space, and then running `gitx` in the terminal, which then works without error.

I did attempt to remedy it by re-installing the command line feature, but this had no effect.

**Comment by hannesa2** [comment] 2023-04-18 04:23
duplicate of 
https://github.com/gitx/gitx/issues/397#issuecomment-1503146375
https://github.com/gitx/gitx/issues/399#issuecomment-1509335273
https://github.com/gitx/gitx/issues/398#issuecomment-1504737043

**Closed by hannesa2** 2023-04-18 04:23 UTC

**Comment by chief1983** [comment] 2023-04-18 16:14
Sorry, didn't see an open one recently, should have checked closed too.  Mea culpa.
