### ISSUE TITLE
Take over homebrew formula

### ISSUE THREAD

**Issue by jasonkarns** [gitx/gitx#113] opened 2018-02-02 22:26 UTC
It would be great if gitx on homebrew were this fork now that the others are dead. At the very least, this github org could host its own tap for this build of gitx.

**Comment by bf4** [comment] 2019-01-03 15:34
I just made one, though I haven't tested it beyond that it installed for me on Sierra

I basically copied the rowanj-gitx formula since it was the later one

```ruby
cask 'gitx-gitx' do
  # github.com/gitx/gitx was verified as official when first introduced to the cask
  if MacOS.version <= :snow_leopard
    version '0.14.81'
    sha256 'ba61b4b84cb613a6196e6bd1d3102ad460ec0645a885b1cb94132e5244e1d330'
    url "https://github.com/gitx/gitx/releases/download/builds/#{version.major_minor}/#{version.patch}/GitX-dev-#{version.patch}.dmg"
  elsif MacOS.version <= :lion
    version '0.15.1949'
    sha256 '17301ee1209bd4b12c126d7a58405efdb366f99f70b4f923a9c96e16c334ce2a'
    url "https://github.com/gitx/gitx/releases/download/builds/#{version.major_minor}/#{version.patch}/GitX-dev-#{version.patch}.dmg"
  elsif MacOS.version <= :mavericks
    version '0.15.1964'
    sha256 'd88bcb7f92ca1cdf31cb3f1d2e24c03e2091ab330319aeef2e770c0dbd6f7817'
    url "https://github.com/gitx/gitx/releases/download/builds/#{version.major_minor}/#{version.patch}/GitX-dev-#{version.patch}.dmg"
  else
    version '0.16.2327'
    sha256 'c8dd6dcac8dd85808acdb937f3125bf67b2b1c2b36da5541f20de73628abf544'
    url "https://github.com/gitx/gitx/releases/download/build%2F#{version.major_minor}%2F#{version.patch}/GitX-dev-#{version.patch}.dmg"
  end

  appcast 'https://github.com/gitx/gitx/releases.atom'
  name 'GitX-dev'
  homepage 'https://github.com/gitx/gitx'

  conflicts_with cask: %w[
    gitx
    laullon-gitx
    rowanj-gitx
  ]

  app 'GitX.app'
  binary "#{appdir}/GitX.app/Contents/Resources/gitx"
end

```

**Comment by bf4** [comment] 2019-01-03 15:40
duplicate of https://github.com/gitx/gitx/issues/147

**Comment by bf4** [comment] 2019-01-03 15:43
I think to make a tap we'd need a new repo 

https://github.com/gitx/homebrew-gitx

with just a file `gitx.rb`

then people could `brew install gitx/gitx/gitx`

and we'd just replace the `cask` block above with

```ruby
class Gitx < Formula
end
```

**Comment by pshirshov** [comment] 2019-10-18 11:05
Sorry about intrustion, but is anyone working on this?

**Comment by bf4** [comment] 2019-10-18 14:33
cc @tiennou

**Comment by pshirshov** [comment] 2019-10-20 11:39
Eh. I think I may start publishing it to the app store in case there will be no easy way to install it :(

**Comment by plan44** [comment] 2019-10-20 18:33
I'm only very loosely following the discussion, but I'd welcome _any_ step that would make all the good work apparently happening here more accessible.

Building from sources seems difficult these days (failed the last few times I tried, despite I'm quite familiar with XCode), and with no easy way to install it otherwise, I'm still using a version from 2yrs ago :-(

**Comment by tiennou** [comment] 2019-10-21 20:45
Builds from master should be fine on Xcode 11, but I'm the one with the mostly working setup, and I don't understand what's causing the failures on other machines… I'm having issues code-signing as well, so I'm attaching an unsigned debug build :wink:.

[GitX.zip](https://github.com/gitx/gitx/files/3752827/GitX.zip)

**Comment by pshirshov** [comment] 2019-10-21 22:38
> Builds from master should be fine on Xcode 11

Oh, they aren't. Primary offender is improperly configured objective-git which references openssl as dylibs instead of embedding them directly.

In the other ticket I've attached properly notarized and 100% working build, feel free to use it...

**Comment by tiennou** [comment] 2019-10-22 11:11
I'm trying to pinpoint what's going on, so can someone confirm how the GitX.app above work for them ? I've just been running GitX under the debugger this morning, so I'm 100% confident master *builds and runs*. I want to know what's different on my machine now.

**Comment by bf4** [comment] 2019-10-24 02:58
@tiennou If you make a homebrew tap I'll help set it up https://github.com/gitx/gitx/issues/113#issuecomment-451182027 https://github.com/gitx/gitx/issues/113#issuecomment-451178980

**Comment by niksy** [comment] 2020-01-09 09:03
Is anyone working on this?

**Comment by bcomnes** [comment] 2020-01-17 20:11
> so I'm 100% confident master builds and runs

Perhaps it's environmental?  afaict, homebrew has changed the location openssl is installed which hoses the current build process.

**Comment by pvinis** [comment] 2020-01-19 22:20
I didn't, and even though I love GitX, I now only use it rarely, so I haven't bothered to set this up.

**Comment by jasonkarns** [comment] 2020-03-28 16:01
It's not strictly necessary to have a separate repo for the formula. In the interim of having our own tap, users can install using a url to the raw formula:

eg `brew install https://raw.githubusercontent.com/gitx/gitx/path/to/formula.rb`

(And for whomever _does_ create the tap, FYI there is a command to generate the scaffolding for the tap: `brew tap-new gitx/homebrew-gitx`)

**Comment by hannesa2** [comment] 2022-03-07 07:46
It depends on https://github.com/gitx/gitx/issues/278

**Comment by TomHoenderdos** [comment] 2022-09-22 08:01
Seems #278 is now closed, what can we do to help this move forward? I already forked the formulae.brew.sh repo and I can create a PR for the change needed if you want

**Comment by hannesa2** [comment] 2022-09-22 08:17
I guess https://github.com/gitx/gitx/issues/284 is the same topic

**Comment by miccal** [comment] 2023-02-21 23:22
https://github.com/Homebrew/homebrew-cask/pull/141659

**Comment by miccal** [comment] 2023-02-22 08:10
https://github.com/Homebrew/homebrew-cask/pull/141659#issuecomment-1439584247

**Comment by hannesa2** [comment] 2023-02-24 16:56
https://github.com/Homebrew/homebrew-cask/pull/141659 is merged now. Is there more to do on our side, or can we close this now ?

**Closed** 2023-02-25 05:31 UTC
